---
title: "Git Out Markdown"
author: "Git Out"
output:
  prettydoc::html_pretty:
  theme: architect
  toc: true
date: "12 Dec 2025"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
DATA <- read.csv(here("data.csv"))
library(ggplot2)
library(kableExtra)
```

#Physical and Mental Health Outcomes Across Research Sites


##Cleaning A Example
```{r setup, include=TRUE}

#Cleaning A
dim(A.data)
str(A.data)
head(A.data)

A.data$PH <- ifelse(A.data$PH == "Y", 1, ifelse(A.data$PH == "N", 0, A.data$PH))
A.data$MH <- ifelse(A.data$MH == "Y", 1, ifelse(A.data$MH == "N", 0, A.data$MH))
A.data$Smoker <- ifelse(A.data$Smoker == "Y", 1, ifelse(A.data$Smoker == "Current", 1, ifelse(A.data$Smoker == "N", 0, A.data$MH)))
A.data$SES5 <- ifelse(
  A.data$SES5 == "L1", 1,
  ifelse(A.data$SES5 == "L2", 2,
         ifelse(A.data$SES5 == "L3", 3,
                ifelse(A.data$SES5 == "L4", 4,
                       ifelse(A.data$SES5 == "L5", 5, A.data$SES5)
                )
         )
  )
)

dim(A.data)
str(A.data)
head(A.data)


```


##Binomial Analysis

##Secondary Analysis

#Conclusion

There are some sick people. We can't save them all. 